name: Sanity Check
on:
  push:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: "${{ ((inputs.git_ref) && inputs.git_ref) || github.ref }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          make verify-prerequisites deps NO_VENV=1

      - name: Lint
        run: make lint NO_VENV=1

      - name: Run build to make sure it works
        run: make build NO_VENV=1
